2020-06-30 19:56:34,749 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNTkzNTYxOTg2LjI0NTI3OX0.WLdXvCbxUlGqfhQSR7Dc4unjKGrPBhwWM98FMxDomC8 [GET] [in /Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/app/routes.py", line 188, in reset_password
    return render_template('reset_password.html', form=form)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/app/templates/reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/connorreitz/Documents/Programming/flask_webapp/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/connorreitz/Documents/Programming/flask_webapp/app/templates/reset_password.html", line 15, in block "content"
    {{ form.password2.label }}<br>
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordForm object' has no attribute 'password2'
2020-06-30 19:57:21,989 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNTkzNTYyMDM0LjE1NzUyMn0.tLKEVWEIpMppWkMWqbSrfvmWv9dPBG0VjWlN7hUIJEc [GET] [in /Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/app/routes.py", line 188, in reset_password
    return render_template('reset_password.html', form=form)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/app/templates/reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/connorreitz/Documents/Programming/flask_webapp/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/connorreitz/Documents/Programming/flask_webapp/app/templates/reset_password.html", line 15, in block "content"
    {{ form.repeat_password.label }}<br>
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordForm object' has no attribute 'password2'
2020-06-30 21:51:14,690 INFO: Reitz Recipes startup [in /Users/connorreitz/Documents/Programming/flask_webapp/app/__init__.py:50]
2020-06-30 21:51:32,016 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNTkzNTY4ODg0LjU2OTkxMzF9.Fq4-kXE07yqlN2YLPZBcRV8LchLJeZGcakDevTsiqKc [GET] [in /Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/app/routes.py", line 188, in reset_password
    return render_template('reset_password.html', form=form)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/connorreitz/Documents/Programming/flask_webapp/app/templates/reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/connorreitz/Documents/Programming/flask_webapp/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/connorreitz/Documents/Programming/flask_webapp/app/templates/reset_password.html", line 15, in block "content"
    {{ form.repeat_password.label }}<br>
  File "/Users/connorreitz/Documents/Programming/flask_webapp/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordForm object' has no attribute 'repeat_password'
2020-06-30 21:52:18,162 INFO: Reitz Recipes startup [in /Users/connorreitz/Documents/Programming/flask_webapp/app/__init__.py:50]
